### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by DJam98** [offthedial/site#15]
> *Edited by @LeptoFlare*

A togglable dark mode for the site.

#### Features Include:
- [ ] The user should be able to click a toggle to switch between Light and Dark mode.
- [ ] The user's preference should be saved, so that future visits use the correct color theme.
- [ ] It should default to the user's "preferred" color scheme, according to their operating system settings. If not set, it should default to Light.
- [ ] The site should not flicker on first load, even if the user has selected a non-default color theme.
- [ ] The site should never show the wrong toggle state.

> - https://joshwcomeau.com/gatsby/dark-mode/
> - https://bulma.io/2019/10/15/light-dark-colors/#scheme-variables-for-dark-mode

**Comment by LeptoFlare** [comment]
Primary Background Color: `#282c35`
