### ISSUE TITLE
Brand Assets

### ISSUE THREAD

**Issue by DJam98** [offthedial/site#33]
Just realised this, but we're actually misusing every single one of the media icons terms of service at the bottom of the website.

More specifically, the colour. The green that we have can't be used per their brand guidelines. So for the meantime, could you just disable the green and just make it their own colours (the red for YouTube ect).

We'll discuss what we can do later, but this needs to be done ASAP. Just make the hover colour the default colour.

**Comment by LeptoFlare** [comment]
The media icons at the bottom are not official brand assets, as that would be against tos.

They are Font Awesome icons (see https://fontawesome.com) which have a different license.

**Comment by DJam98** [comment]
Cool, sorted then!
